alias c='cd .. && pwd'
alias ..='cd ../.. && pwd'
alias ...='cd ../../.. && pwd'
alias ....='cd ../../../.. && pwd'
alias .....='cd ../../../../.. && pwd'
alias d='du -hs'
alias e='logout'
alias f='grep --color=always'
alias g='ga ; gcm ; gp'
alias gca='git commit -a'
alias gcam='git commit -am'
alias h='history >> $HOME/.historyfile'
alias j='jobs'
alias i='whoami'
alias l='ls -al --color=always'
alias lr='ls -alR --color=always'
alias p='pwd'
alias pacman='pacman --color=always'
alias pcs='pacman -S --color=always'
alias pcss='pacman -Ss --color=always'
alias q='logout'
alias rf='rm -rf'
